services:
  php:
    container_name: php
    image: ${IMAGES_PREFIX:-}app-php
    environment:
      TRUSTED_PROXIES: ${TRUSTED_PROXIES:-127.0.0.0/8,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16}
      TRUSTED_HOSTS: ${TRUSTED_HOSTS:-^${SERVER_NAME:-example\.com|localhost}|php$$}
      DATABASE_URL: mysql://${MYSQL_USER:-app}:${MYSQL_PASSWORD:-!ChangeMe!}@database:3306/${MYSQL_DB:-app}?serverVersion=mariadb-10.6.4&charset=utf8mb4
      MERCURE_URL: ${CADDY_MERCURE_URL:-http://php/.well-known/mercure}
      MERCURE_PUBLIC_URL: ${CADDY_MERCURE_PUBLIC_URL:-https://${SERVER_NAME:-localhost}/.well-known/mercure}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET:-!ChangeThisMercureHubJWTSecretKey!}
      CORS_ALLOW_ORIGIN: "^https?://(localhost|127.0.0.1)(:[0-9]+)?$"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    depends_on:
      database:
        condition: service_healthy
  
  database:
    image: mariadb:${MARIADB_VERSION:-10.6.4}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-!ChangeMe!}
      MYSQL_DATABASE: ${MYSQL_DB:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "--host=127.0.0.1",
          "--user=${MYSQL_USER:-app}",
          "--password=${MYSQL_PASSWORD:-!ChangeMe!}",
        ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - target: 80
        published: ${PMA_PORT:-8080}
        protocol: tcp
    depends_on:
      - database
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
  database_data:
